package com.weilaios.iqxceqhnhubt.model;

import com.baomidou.mybatisplus.annotation.TableField;
import com.baomidou.mybatisplus.annotation.TableId;

import java.sql.Timestamp;
import java.util.Date;

public class EntityRelation {
    /**
     * 主键编号
     * @mbggenerated
     */
    @TableId
    private String uuid;

    /**
     * 创建时间
     * @mbggenerated
     */
    private Timestamp createTime;

    /**
     * 是否删除 0 否 1 是
     * @mbggenerated
     */
    private String isDeleted;

    /**
     * 左关联实体主键
     * @mbggenerated
     */
    private String leftEntityUuid;

    /**
     * 右关联实体主键
     * @mbggenerated
     */
    private String rightEntityUuid;

    /**
     * 关联类型  关系类型 1 - 一:一 2 - 一:多 3 - 多:一 4 - 多:多
     * @mbggenerated
     */
    private String type;

    /**
     * 左关联字段
     * @mbggenerated
     */
    private String leftRelationField;

    /**
     * 右关联字段
     * @mbggenerated
     */
    private String rightRelationField;

    /**
     * 关联名称
     * @mbggenerated
     */
    private String name;

    /**
     * 项目编号
     * @mbggenerated
     */
    private String projectUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wlos_entity_relation.relation_key
     *
     * @mbggenerated
     */
    private String relationKey;

    /**
     * 左表显示字段
     * @mbggenerated
     */
    private String leftShowField;

    /**
     * 右表显示字段
     * @mbggenerated
     */
    private String rightShowField;

    public Integer getIsDefault() {
        return isDefault;
    }

    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * 是否是自定义实体与系统实体建建立的关系
     * @return
     */
    private Integer isDefault;

    public String getOrigin() {
        return origin;
    }

    public void setOrigin(String origin) {
        this.origin = origin;
    }

    /**
     * 该关系来自于哪个多对多关系
     */
    private String origin;


    public String getLeftEngine() {
        return leftEngine;
    }

    public String getRightEngine() {
        return rightEngine;
    }

    public void setLeftEngine(String leftEngine) {
        this.leftEngine = leftEngine;
    }

    public void setRightEngine(String rightEngine) {
        this.rightEngine = rightEngine;
    }

    private String leftEngine;
    private String rightEngine;


    public String getLeftName() {
        return leftName;
    }

    public String getRightName() {
        return rightName;
    }

    public void setLeftName(String leftName) {
        this.leftName = leftName;
    }

    public void setRightName(String rightName) {
        this.rightName = rightName;
    }

    @TableField(exist = false)
    private String leftName;
    @TableField(exist = false)
    private String rightName;

    public String getMidEntityEnName() {
        return midEntityEnName;
    }

    public void setMidEntityEnName(String midEntityEnName) {
        this.midEntityEnName = midEntityEnName;
    }


    private String midEntityEnName;
    @TableField(exist = false)
    private String rightTableName;
    private Integer rightDeleteRole;
    private Integer leftDeleteRole;
    public String getSysLevel() {
        return sysLevel;
    }

    public void setSysLevel(String sysLevel) {
        this.sysLevel = sysLevel;
    }

    private String sysLevel;

    public Integer getLeftDeleteAnyway() {
        return leftDeleteAnyway;
    }

    public Integer getRightDeleteAnyway() {
        return rightDeleteAnyway;
    }

    public void setLeftDeleteAnyway(Integer leftDeleteAnyway) {
        this.leftDeleteAnyway = leftDeleteAnyway;
    }

    public void setRightDeleteAnyway(Integer rightDeleteAnyway) {
        this.rightDeleteAnyway = rightDeleteAnyway;
    }

    private Integer leftDeleteAnyway;
    private Integer rightDeleteAnyway;


    public void setRightDeleteRole(Integer rightDeleteRole) {
        this.rightDeleteRole = rightDeleteRole;
    }

    public void setLeftDeleteRole(Integer leftDeleteRole) {
        this.leftDeleteRole = leftDeleteRole;
    }


    public Integer getRightDeleteRole() {
        return rightDeleteRole;
    }

    public Integer getLeftDeleteRole() {
        return leftDeleteRole;
    }

    public String getRightTableName() {
        return rightTableName;
    }

    public void setRightTableName(String rightTableName) {
        this.rightTableName = rightTableName;
    }

    /**
     * 标识左右表的查找字段来源
     */
    public Integer leftSource;
    public Integer rightSource;

    public Integer getLeftSource() {
        return leftSource;
    }

    public void setLeftSource(Integer leftSource) {
        this.leftSource = leftSource;
    }

    public Integer getRightSource() {
        return rightSource;
    }

    public void setRightSource(Integer rightSource) {
        this.rightSource = rightSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.uuid
     *
     * @return the value of wlos_entity_relation.uuid
     *
     * @mbggenerated
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.uuid
     *
     * @param uuid the value for wlos_entity_relation.uuid
     *
     * @mbggenerated
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.create_time
     *
     * @return the value of wlos_entity_relation.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.create_time
     *
     * @param createTime the value for wlos_entity_relation.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.is_deleted
     *
     * @return the value of wlos_entity_relation.is_deleted
     *
     * @mbggenerated
     */
    public String getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.is_deleted
     *
     * @param isDeleted the value for wlos_entity_relation.is_deleted
     *
     * @mbggenerated
     */
    public void setIsDeleted(String isDeleted) {
        this.isDeleted = isDeleted == null ? null : isDeleted.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.left_entity_uuid
     *
     * @return the value of wlos_entity_relation.left_entity_uuid
     *
     * @mbggenerated
     */
    public String getLeftEntityUuid() {
        return leftEntityUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.left_entity_uuid
     *
     * @param leftEntityUuid the value for wlos_entity_relation.left_entity_uuid
     *
     * @mbggenerated
     */
    public void setLeftEntityUuid(String leftEntityUuid) {
        this.leftEntityUuid = leftEntityUuid == null ? null : leftEntityUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.right_entity_uuid
     *
     * @return the value of wlos_entity_relation.right_entity_uuid
     *
     * @mbggenerated
     */
    public String getRightEntityUuid() {
        return rightEntityUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.right_entity_uuid
     *
     * @param rightEntityUuid the value for wlos_entity_relation.right_entity_uuid
     *
     * @mbggenerated
     */
    public void setRightEntityUuid(String rightEntityUuid) {
        this.rightEntityUuid = rightEntityUuid == null ? null : rightEntityUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.type
     *
     * @return the value of wlos_entity_relation.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.type
     *
     * @param type the value for wlos_entity_relation.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.left_relation_field
     *
     * @return the value of wlos_entity_relation.left_relation_field
     *
     * @mbggenerated
     */
    public String getLeftRelationField() {
        return leftRelationField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.left_relation_field
     *
     * @param leftRelationField the value for wlos_entity_relation.left_relation_field
     *
     * @mbggenerated
     */
    public void setLeftRelationField(String leftRelationField) {
        this.leftRelationField = leftRelationField == null ? null : leftRelationField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.right_relation_field
     *
     * @return the value of wlos_entity_relation.right_relation_field
     *
     * @mbggenerated
     */
    public String getRightRelationField() {
        return rightRelationField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.right_relation_field
     *
     * @param rightRelationField the value for wlos_entity_relation.right_relation_field
     *
     * @mbggenerated
     */
    public void setRightRelationField(String rightRelationField) {
        this.rightRelationField = rightRelationField == null ? null : rightRelationField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.name
     *
     * @return the value of wlos_entity_relation.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.name
     *
     * @param name the value for wlos_entity_relation.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.project_uuid
     *
     * @return the value of wlos_entity_relation.project_uuid
     *
     * @mbggenerated
     */
    public String getProjectUuid() {
        return projectUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.project_uuid
     *
     * @param projectUuid the value for wlos_entity_relation.project_uuid
     *
     * @mbggenerated
     */
    public void setProjectUuid(String projectUuid) {
        this.projectUuid = projectUuid == null ? null : projectUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.relation_key
     *
     * @return the value of wlos_entity_relation.relation_key
     *
     * @mbggenerated
     */
    public String getRelationKey() {
        return relationKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.relation_key
     *
     * @param relationKey the value for wlos_entity_relation.relation_key
     *
     * @mbggenerated
     */
    public void setRelationKey(String relationKey) {
        this.relationKey = relationKey == null ? null : relationKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.left_show_field
     *
     * @return the value of wlos_entity_relation.left_show_field
     *
     * @mbggenerated
     */
    public String getLeftShowField() {
        return leftShowField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.left_show_field
     *
     * @param leftShowField the value for wlos_entity_relation.left_show_field
     *
     * @mbggenerated
     */
    public void setLeftShowField(String leftShowField) {
        this.leftShowField = leftShowField == null ? null : leftShowField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wlos_entity_relation.right_show_field
     *
     * @return the value of wlos_entity_relation.right_show_field
     *
     * @mbggenerated
     */
    public String getRightShowField() {
        return rightShowField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wlos_entity_relation.right_show_field
     *
     * @param rightShowField the value for wlos_entity_relation.right_show_field
     *
     * @mbggenerated
     */
    public void setRightShowField(String rightShowField) {
        this.rightShowField = rightShowField == null ? null : rightShowField.trim();
    }

   

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wlos_entity_relation
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUuid() == null) ? 0 : getUuid().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getIsDeleted() == null) ? 0 : getIsDeleted().hashCode());
        result = prime * result + ((getLeftEntityUuid() == null) ? 0 : getLeftEntityUuid().hashCode());
        result = prime * result + ((getRightEntityUuid() == null) ? 0 : getRightEntityUuid().hashCode());
        result = prime * result + ((getType() == null) ? 0 : getType().hashCode());
        result = prime * result + ((getLeftRelationField() == null) ? 0 : getLeftRelationField().hashCode());
        result = prime * result + ((getRightRelationField() == null) ? 0 : getRightRelationField().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getProjectUuid() == null) ? 0 : getProjectUuid().hashCode());
        result = prime * result + ((getRelationKey() == null) ? 0 : getRelationKey().hashCode());
        result = prime * result + ((getLeftShowField() == null) ? 0 : getLeftShowField().hashCode());
        result = prime * result + ((getRightShowField() == null) ? 0 : getRightShowField().hashCode());
        return result;
    }
}